SELECT [ID], [PREFERENCE_TYPE], [PREFERENCE_VALUE] 
FROM [CUSTOMER_PREFERENCES] 
WHERE [IsDeleted] = 0 
	AND [CUSTOMER_ID] = @PRM_CUSTOMER_PREFERENCE_CUSTOMER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 