//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.CustomerManagementModule.Application.Dtos.CustomerPreference;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.CustomerManagementModule.Application.Mappings
{
    public static class CustomerPreferenceMappings
    {
        public static List<CustomerPreferenceDto> ToDto(this IEnumerable<CustomerPreference> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CustomerPreferenceDto ToDto(this CustomerPreference model)
        {
            return new CustomerPreferenceDto
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                PreferenceType = model.PreferenceType,
                PreferenceValue = model.PreferenceValue
            };
        }

        public static CustomerPreference ToEntity(this CustomerPreferenceDto model)
        {
            return new CustomerPreference
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                PreferenceType = model.PreferenceType,
                PreferenceValue = model.PreferenceValue
            };
        }
    }
}