//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.CustomerManagementModule.Application.Dtos.Customer;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.CustomerManagementModule.Application.Mappings
{
    public static class CustomerMappings
    {
        public static List<CustomerDto> ToDto(this IEnumerable<Customer> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CustomerDto ToDto(this Customer model)
        {
            return new CustomerDto
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                PhoneNumber = model.PhoneNumber,
                LoyaltyTier = model.LoyaltyTier,
                Notes = model.Notes,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static Customer ToEntity(this CustomerDto model)
        {
            return new Customer
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                PhoneNumber = model.PhoneNumber,
                LoyaltyTier = model.LoyaltyTier,
                Notes = model.Notes,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}