//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.CustomerManagementModule.Application.Dtos.CustomerAddress;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.CustomerManagementModule.Application.Mappings
{
    public static class CustomerAddressMappings
    {
        public static List<CustomerAddressDto> ToDto(this IEnumerable<CustomerAddress> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CustomerAddressDto ToDto(this CustomerAddress model)
        {
            return new CustomerAddressDto
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                AddressLine1 = model.AddressLine1,
                AddressLine2 = model.AddressLine2,
                City = model.City,
                State = model.State,
                ZipCode = model.ZipCode,
                Country = model.Country,
                IsDefault = model.IsDefault
            };
        }

        public static CustomerAddress ToEntity(this CustomerAddressDto model)
        {
            return new CustomerAddress
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                AddressLine1 = model.AddressLine1,
                AddressLine2 = model.AddressLine2,
                City = model.City,
                State = model.State,
                ZipCode = model.ZipCode,
                Country = model.Country,
                IsDefault = model.IsDefault
            };
        }
    }
}