//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.CustomerManagementModule.Application.Dtos.LoyaltyProgram;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.CustomerManagementModule.Application.Mappings
{
    public static class LoyaltyProgramMappings
    {
        public static List<LoyaltyProgramDto> ToDto(this IEnumerable<LoyaltyProgram> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static LoyaltyProgramDto ToDto(this LoyaltyProgram model)
        {
            return new LoyaltyProgramDto
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                PointsPerDollar = model.PointsPerDollar
            };
        }

        public static LoyaltyProgram ToEntity(this LoyaltyProgramDto model)
        {
            return new LoyaltyProgram
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                PointsPerDollar = model.PointsPerDollar
            };
        }
    }
}