SELECT [ID], [APPOINTMENT_ID], [REMINDER_TIME] 
FROM [APPOINTMENT_REMINDERS] 
WHERE [IsDeleted] = 0 
	AND [IS_SENT] = @PRM_APPOINTMENT_REMINDER_IS_SENT 
	AND [REMINDER_TIME] < GETDATE() 
ORDER BY [ID] 