SELECT [ID], [NAME], [DESCRIPTION], [PRICE], [CATEGORY], [DURATION_MINUTES] 
FROM [SERVICES] 
WHERE [IsDeleted] = 0 
	AND [HAIRDRESSER_ID] = @PRM_SERVICE_HAIRDRESSER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 