SELECT [ID], [HAIRDRESSER_ID], [NAME], [DESCRIPTION], [PRICE], [DURATION_MINUTES] 
FROM [SERVICES] 
WHERE [IsDeleted] = 0 
	AND [CATEGORY] = @PRM_SERVICE_CATEGORY 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 