//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Dtos.HairdresserNote;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Entities;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.HairdresserManagementModule.Application.Mappings
{
    public static class HairdresserNoteMappings
    {
        public static List<HairdresserNoteDto> ToDto(this IEnumerable<HairdresserNote> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static HairdresserNoteDto ToDto(this HairdresserNote model)
        {
            return new HairdresserNoteDto
            {
                Id = model.Id,
                HairdresserId = model.HairdresserId,
                Note = model.Note,
                CreatedDate = model.CreatedDate
            };
        }

        public static HairdresserNote ToEntity(this HairdresserNoteDto model)
        {
            return new HairdresserNote
            {
                Id = model.Id,
                HairdresserId = model.HairdresserId,
                Note = model.Note,
                CreatedDate = model.CreatedDate
            };
        }
    }
}