//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Dtos.Hairdresser;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Entities;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.HairdresserManagementModule.Application.Mappings
{
    public static class HairdresserMappings
    {
        public static List<HairdresserDto> ToDto(this IEnumerable<Hairdresser> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static HairdresserDto ToDto(this Hairdresser model)
        {
            return new HairdresserDto
            {
                Id = model.Id,
                Name = model.Name,
                Email = model.Email,
                PhoneNumber = model.PhoneNumber,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static Hairdresser ToEntity(this HairdresserDto model)
        {
            return new Hairdresser
            {
                Id = model.Id,
                Name = model.Name,
                Email = model.Email,
                PhoneNumber = model.PhoneNumber,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}