//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Dtos.ServicePrice;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Entities;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.HairdresserManagementModule.Application.Mappings
{
    public static class ServicePriceMappings
    {
        public static List<ServicePriceDto> ToDto(this IEnumerable<ServicePrice> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ServicePriceDto ToDto(this ServicePrice model)
        {
            return new ServicePriceDto
            {
                Id = model.Id,
                ServiceId = model.ServiceId,
                Price = model.Price,
                ValidFrom = model.ValidFrom,
                ValidTo = model.ValidTo
            };
        }

        public static ServicePrice ToEntity(this ServicePriceDto model)
        {
            return new ServicePrice
            {
                Id = model.Id,
                ServiceId = model.ServiceId,
                Price = model.Price,
                ValidFrom = model.ValidFrom,
                ValidTo = model.ValidTo
            };
        }
    }
}