//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Dtos.Service;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Entities;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.HairdresserManagementModule.Application.Mappings
{
    public static class ServiceMappings
    {
        public static List<ServiceDto> ToDto(this IEnumerable<Service> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ServiceDto ToDto(this Service model)
        {
            return new ServiceDto
            {
                Id = model.Id,
                HairdresserId = model.HairdresserId,
                Name = model.Name,
                Description = model.Description,
                Price = model.Price,
                Category = model.Category,
                DurationMinutes = model.DurationMinutes
            };
        }

        public static Service ToEntity(this ServiceDto model)
        {
            return new Service
            {
                Id = model.Id,
                HairdresserId = model.HairdresserId,
                Name = model.Name,
                Description = model.Description,
                Price = model.Price,
                Category = model.Category,
                DurationMinutes = model.DurationMinutes
            };
        }
    }
}