SELECT [ID], [LOYALTY_PROGRAM_ID], [POINTS] 
FROM [CUSTOMER_LOYALTY_POINTS] 
WHERE [IsDeleted] = 0 
	AND [CUSTOMER_ID] = @PRM_CUSTOMER_LOYALTY_POINT_CUSTOMER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 