//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Dtos.AppointmentReminder;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Entities;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.AppointmentManagementModule.Application.Mappings
{
    public static class AppointmentReminderMappings
    {
        public static List<AppointmentReminderDto> ToDto(this IEnumerable<AppointmentReminder> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AppointmentReminderDto ToDto(this AppointmentReminder model)
        {
            return new AppointmentReminderDto
            {
                Id = model.Id,
                AppointmentId = model.AppointmentId,
                ReminderTime = model.ReminderTime,
                IsSent = model.IsSent
            };
        }

        public static AppointmentReminder ToEntity(this AppointmentReminderDto model)
        {
            return new AppointmentReminder
            {
                Id = model.Id,
                AppointmentId = model.AppointmentId,
                ReminderTime = model.ReminderTime,
                IsSent = model.IsSent
            };
        }
    }
}