//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Dtos.AppointmentCharge;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Entities;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.AppointmentManagementModule.Application.Mappings
{
    public static class AppointmentChargeMappings
    {
        public static List<AppointmentChargeDto> ToDto(this IEnumerable<AppointmentCharge> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AppointmentChargeDto ToDto(this AppointmentCharge model)
        {
            return new AppointmentChargeDto
            {
                Id = model.Id,
                AppointmentId = model.AppointmentId,
                ChargeType = model.ChargeType,
                Amount = model.Amount
            };
        }

        public static AppointmentCharge ToEntity(this AppointmentChargeDto model)
        {
            return new AppointmentCharge
            {
                Id = model.Id,
                AppointmentId = model.AppointmentId,
                ChargeType = model.ChargeType,
                Amount = model.Amount
            };
        }
    }
}