//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Dtos.AppointmentFeedback;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Entities;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.AppointmentManagementModule.Application.Mappings
{
    public static class AppointmentFeedbackMappings
    {
        public static List<AppointmentFeedbackDto> ToDto(this IEnumerable<AppointmentFeedback> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AppointmentFeedbackDto ToDto(this AppointmentFeedback model)
        {
            return new AppointmentFeedbackDto
            {
                Id = model.Id,
                AppointmentId = model.AppointmentId,
                Rating = model.Rating,
                Comments = model.Comments,
                CreatedDate = model.CreatedDate
            };
        }

        public static AppointmentFeedback ToEntity(this AppointmentFeedbackDto model)
        {
            return new AppointmentFeedback
            {
                Id = model.Id,
                AppointmentId = model.AppointmentId,
                Rating = model.Rating,
                Comments = model.Comments,
                CreatedDate = model.CreatedDate
            };
        }
    }
}