//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Dtos.Holiday;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Entities;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.AppointmentManagementModule.Application.Mappings
{
    public static class HolidayMappings
    {
        public static List<HolidayDto> ToDto(this IEnumerable<Holiday> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static HolidayDto ToDto(this Holiday model)
        {
            return new HolidayDto
            {
                Id = model.Id,
                HolidayDate = model.HolidayDate,
                Description = model.Description
            };
        }

        public static Holiday ToEntity(this HolidayDto model)
        {
            return new Holiday
            {
                Id = model.Id,
                HolidayDate = model.HolidayDate,
                Description = model.Description
            };
        }
    }
}