//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Dtos.WaitingList;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Entities;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.AppointmentManagementModule.Application.Mappings
{
    public static class WaitingListMappings
    {
        public static List<WaitingListDto> ToDto(this IEnumerable<WaitingList> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static WaitingListDto ToDto(this WaitingList model)
        {
            return new WaitingListDto
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                ServiceId = model.ServiceId,
                PreferredDate = model.PreferredDate,
                Notes = model.Notes
            };
        }

        public static WaitingList ToEntity(this WaitingListDto model)
        {
            return new WaitingList
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                ServiceId = model.ServiceId,
                PreferredDate = model.PreferredDate,
                Notes = model.Notes
            };
        }
    }
}