SELECT P.[ID], P.[NAME], P.[SKU], P.[PRICE] 
FROM [PRODUCTS] P 
	INNER JOIN [PRODUCT_CATEGORIES] PC 
			ON PC.[PRODUCT_ID] = P.[ID] 
WHERE P.[IsDeleted] = 0 
	AND PC.[CATEGORY_ID] = @PRM_PRODUCT_CATEGORIES_CATEGORY_ID 
	AND P.[ID] = @PRM_PRODUCTS_ID 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 