SELECT P.[ID], P.[NAME], P.[SKU], P.[PRICE], P.[STOCK_QUANTITY] 
FROM [PRODUCTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[NAME] LIKE '%' + @PRM_PRODUCT_NAME + '%' 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 