//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoAi.ProductCatalogModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.ProductCatalogModule.Persistence.Contexts;
using QuickCode.DemoAi.ProductCatalogModule.Application.Dtos.Product;
using QuickCode.DemoAi.ProductCatalogModule.Application.Mappings;
using QuickCode.DemoAi.ProductCatalogModule.Persistence.Sql;
using QuickCode.DemoAi.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoAi.ProductCatalogModule.Persistence.Repositories
{
    public partial class ProductRepository : BaseRepository, IProductRepository
    {
        public async Task<RepoResponse<int>> AdjustStockAsync(int productId, AdjustStockRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Product", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Product.Command.AdjustStock);
                var parameters = new
                {
                    PRODUCT_STOCK_QUANTITY = updateRequest.ProductStockQuantity,
                    PRM_PRODUCT_ID = productId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> SetPriceAsync(int productId, SetPriceRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Product", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Product.Command.SetPrice);
                var parameters = new
                {
                    PRODUCT_PRICE = updateRequest.ProductPrice,
                    PRM_PRODUCT_ID = productId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> ActivateAsync(int productId, ActivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Product", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Product.Command.Activate);
                var parameters = new
                {
                    PRM_PRODUCT_ID = productId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> DeactivateAsync(int productId, DeactivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Product", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Product.Command.Deactivate);
                var parameters = new
                {
                    PRM_PRODUCT_ID = productId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}