//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.ShippingModule.Application.Dtos.Shipment;
using QuickCode.DemoAi.ShippingModule.Domain.Entities;
using QuickCode.DemoAi.ShippingModule.Domain.Enums;

namespace QuickCode.DemoAi.ShippingModule.Application.Mappings
{
    public static class ShipmentMappings
    {
        public static List<ShipmentDto> ToDto(this IEnumerable<Shipment> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ShipmentDto ToDto(this Shipment model)
        {
            return new ShipmentDto
            {
                Id = model.Id,
                OrderId = model.OrderId,
                ShippingDate = model.ShippingDate,
                DeliveryDate = model.DeliveryDate,
                ShippingAddress = model.ShippingAddress,
                ShippingMethod = model.ShippingMethod,
                TrackingNumber = model.TrackingNumber,
                Status = model.Status
            };
        }

        public static Shipment ToEntity(this ShipmentDto model)
        {
            return new Shipment
            {
                Id = model.Id,
                OrderId = model.OrderId,
                ShippingDate = model.ShippingDate,
                DeliveryDate = model.DeliveryDate,
                ShippingAddress = model.ShippingAddress,
                ShippingMethod = model.ShippingMethod,
                TrackingNumber = model.TrackingNumber,
                Status = model.Status
            };
        }
    }
}