SELECT TOP 1 S.[ID], S.[SHIPPING_DATE], S.[DELIVERY_DATE], S.[SHIPPING_ADDRESS], S.[SHIPPING_METHOD], S.[TRACKING_NUMBER], S.[STATUS] 
FROM [SHIPMENTS] S 
WHERE S.[IsDeleted] = 0 
	AND S.[ORDER_ID] = @PRM_SHIPMENT_ORDER_ID 
ORDER BY S.[ID] 