SELECT S.[ID], S.[ORDER_ID], S.[SHIPPING_DATE], S.[DELIVERY_DATE], S.[SHIPPING_METHOD], S.[TRACKING_NUMBER] 
FROM [SHIPMENTS] S 
WHERE S.[IsDeleted] = 0 
	AND S.[STATUS] = @PRM_SHIPMENT_STATUS 
ORDER BY S.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 