SELECT [ID], [FIRST_NAME], [LAST_NAME], [EMAIL], [PHONE_NUMBER], [LOYALTY_TIER] 
FROM [CUSTOMERS] 
WHERE [IsDeleted] = 0 
	AND [FIRST_NAME] LIKE '%' + @PRM_CUSTOMER_FIRST_NAME + '%' 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 