//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.ShippingModule.Domain.Enums;

namespace QuickCode.DemoAi.ShippingModule.Application.Dtos.Shipment
{
    public record GetByOrderIdResponseDto
    {
        public int Id { get; init; }
        public DateTime ShippingDate { get; init; }
        public DateTime DeliveryDate { get; init; }
        public string ShippingAddress { get; init; }
        public string ShippingMethod { get; init; }
        public string TrackingNumber { get; init; }
        public ShippingStatus Status { get; init; }
    }
}