SELECT [ID], [PRICE], [VALID_FROM], [VALID_TO] 
FROM [SERVICE_PRICES] 
WHERE [IsDeleted] = 0 
	AND [SERVICE_ID] = @PRM_SERVICE_PRICE_SERVICE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 