//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.IdentityModule.Domain.Entities;
using QuickCode.DemoAi.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.IdentityModule.Persistence.Contexts;
using QuickCode.DemoAi.IdentityModule.Application.Dtos.PermissionGroup;
using QuickCode.DemoAi.IdentityModule.Application.Mappings;
using QuickCode.DemoAi.IdentityModule.Persistence.Sql;
using QuickCode.DemoAi.IdentityModule.Domain.Enums;

namespace QuickCode.DemoAi.IdentityModule.Persistence.Repositories
{
    public partial class PermissionGroupRepository : BaseRepository, IPermissionGroupRepository
    {
        public async Task<RepoResponse<List<GetApiMethodAccessGrantsForPermissionGroupsResponseDto>>> GetApiMethodAccessGrantsForPermissionGroupsAsync(string permissionGroupsName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodAccessGrantsForPermissionGroups", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Query.GetApiMethodAccessGrantsForPermissionGroups);
                var parameters = new
                {
                    permissionGroupsName = permissionGroupsName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodAccessGrantsForPermissionGroupsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PermissionGroup");
            });
        }

        public async Task<RepoResponse<GetApiMethodAccessGrantsForPermissionGroupsResponseDto>> GetApiMethodAccessGrantsForPermissionGroupsDetailsAsync(string permissionGroupsName, string apiMethodAccessGrantsPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodAccessGrantsForPermissionGroupsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Query.GetApiMethodAccessGrantsForPermissionGroupsDetails);
                var parameters = new
                {
                    permissionGroupsName = permissionGroupsName,
                    apiMethodAccessGrantsPermissionGroupName = apiMethodAccessGrantsPermissionGroupName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetApiMethodAccessGrantsForPermissionGroupsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in PermissionGroup");
            });
        }

        public async Task<RepoResponse<List<GetPortalPageAccessGrantsForPermissionGroupsResponseDto>>> GetPortalPageAccessGrantsForPermissionGroupsAsync(string permissionGroupsName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageAccessGrantsForPermissionGroups", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Query.GetPortalPageAccessGrantsForPermissionGroups);
                var parameters = new
                {
                    permissionGroupsName = permissionGroupsName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageAccessGrantsForPermissionGroupsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PermissionGroup");
            });
        }

        public async Task<RepoResponse<GetPortalPageAccessGrantsForPermissionGroupsResponseDto>> GetPortalPageAccessGrantsForPermissionGroupsDetailsAsync(string permissionGroupsName, string portalPageAccessGrantsPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageAccessGrantsForPermissionGroupsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Query.GetPortalPageAccessGrantsForPermissionGroupsDetails);
                var parameters = new
                {
                    permissionGroupsName = permissionGroupsName,
                    portalPageAccessGrantsPermissionGroupName = portalPageAccessGrantsPermissionGroupName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetPortalPageAccessGrantsForPermissionGroupsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in PermissionGroup");
            });
        }

        public async Task<RepoResponse<List<GetAspNetUsersForPermissionGroupsResponseDto>>> GetAspNetUsersForPermissionGroupsAsync(string permissionGroupsName)
        {
            return await ExecuteWithExceptionHandling("GetAspNetUsersForPermissionGroups", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Query.GetAspNetUsersForPermissionGroups);
                var parameters = new
                {
                    permissionGroupsName = permissionGroupsName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetAspNetUsersForPermissionGroupsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PermissionGroup");
            });
        }

        public async Task<RepoResponse<GetAspNetUsersForPermissionGroupsResponseDto>> GetAspNetUsersForPermissionGroupsDetailsAsync(string permissionGroupsName, string aspNetUsersId)
        {
            return await ExecuteWithExceptionHandling("GetAspNetUsersForPermissionGroupsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PermissionGroup.Query.GetAspNetUsersForPermissionGroupsDetails);
                var parameters = new
                {
                    permissionGroupsName = permissionGroupsName,
                    aspNetUsersId = aspNetUsersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetAspNetUsersForPermissionGroupsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in PermissionGroup");
            });
        }
    }
}