//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.OrderManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.OrderManagementModule.Application.Dtos.Order
{
    public record GetHighValueOrdersResponseDto
    {
        public int OrderCount { get; init; }
        public decimal TotalRevenue { get; init; }
    }
}