//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.DemoAi.Portal.Models;
using QuickCode.DemoAi.Portal.Models.CustomerManagementModule;
using QuickCode.DemoAi.Portal.Helpers;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.DemoAi.Common.Nswag.Clients.IdentityModuleApi.Contracts;
using CustomerManagementModuleContracts = QuickCode.DemoAi.Common.Nswag.Clients.CustomerManagementModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.DemoAi.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using AutoRest.Core.Utilities.Collections;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.DemoAi.Portal.Controllers.CustomerManagementModule
{
    [Permission("CustomerManagementModuleLoyaltyPrograms")]
    [Area("CustomerManagementModule")]
    [Route("CustomerManagementModuleLoyaltyPrograms")]
    public partial class LoyaltyProgramsController : BaseController
    {
        private readonly CustomerManagementModuleContracts.ILoyaltyProgramsClient pageClient;
        public LoyaltyProgramsController(CustomerManagementModuleContracts.ILoyaltyProgramsClient pageClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(LoyaltyProgramData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(LoyaltyProgramData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.LoyaltyProgramsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(LoyaltyProgramData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.LoyaltyProgramsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(LoyaltyProgramData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.LoyaltyProgramsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(LoyaltyProgramData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(LoyaltyProgramData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(LoyaltyProgramData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(LoyaltyProgramData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<LoyaltyProgramData> PrepareModel()
        {
            var model = GetModel<LoyaltyProgramData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<LoyaltyProgramData> PrepareModel(LoyaltyProgramData model)
        {
            model.NumberOfRecord = await pageClient.LoyaltyProgramsCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.LoyaltyProgramsListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }
    }
}