SELECT CI.[ID], CI.[PRODUCT_ID], CI.[QUANTITY], CI.[PRICE] 
FROM [CART_ITEMS] CI 
WHERE CI.[IsDeleted] = 0 
	AND CI.[CART_ID] = @PRM_CART_ITEM_CART_ID 
ORDER BY CI.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 