//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoAi.ProductCatalogModule.Application.Dtos.Category;
using System.Threading.Tasks;
using QuickCode.DemoAi.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoAi.ProductCatalogModule.Application.Interfaces.Repositories
{
    public partial interface ICategoryRepository : IBaseRepository<CategoryDto>
    {
        Task<RepoResponse<CategoryDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool categoryIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string categoryName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> DeactivateAsync(int categoryId, DeactivateRequestDto updateRequest);
    }
}