//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoAi.ProductCatalogModule.Application.Dtos.ProductCategory;
using System.Threading.Tasks;
using QuickCode.DemoAi.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoAi.ProductCatalogModule.Application.Interfaces.Repositories
{
    public partial interface IProductCategoryRepository : IBaseRepository<ProductCategoryDto>
    {
        Task<RepoResponse<ProductCategoryDto>> GetByPkAsync(int productId, int categoryId);
        Task<RepoResponse<List<GetByProductIdResponseDto>>> GetByProductIdAsync(int productCategoryProductId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByCategoryIdResponseDto>>> GetByCategoryIdAsync(int productCategoryCategoryId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> RemoveCategoryAsync(int productCategoryProductId, int productCategoryCategoryId);
    }
}