//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Entities;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Dtos.Hairdresser;
using System.Threading.Tasks;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.HairdresserManagementModule.Application.Interfaces.Repositories
{
    public partial interface IHairdresserRepository : IBaseRepository<HairdresserDto>
    {
        Task<RepoResponse<HairdresserDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool hairdresserIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string hairdresserName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetServicesForHairdressersResponseDto>>> GetServicesForHairdressersAsync(int hairdressersId);
        Task<RepoResponse<GetServicesForHairdressersResponseDto>> GetServicesForHairdressersDetailsAsync(int hairdressersId, int servicesId);
        Task<RepoResponse<List<GetHairdresserAvailabilitiesForHairdressersResponseDto>>> GetHairdresserAvailabilitiesForHairdressersAsync(int hairdressersId);
        Task<RepoResponse<GetHairdresserAvailabilitiesForHairdressersResponseDto>> GetHairdresserAvailabilitiesForHairdressersDetailsAsync(int hairdressersId, int hairdresserAvailabilitiesId);
        Task<RepoResponse<List<GetHairdresserNotesForHairdressersResponseDto>>> GetHairdresserNotesForHairdressersAsync(int hairdressersId);
        Task<RepoResponse<GetHairdresserNotesForHairdressersResponseDto>> GetHairdresserNotesForHairdressersDetailsAsync(int hairdressersId, int hairdresserNotesId);
        Task<RepoResponse<int>> ActivateAsync(int hairdresserId, ActivateRequestDto updateRequest);
        Task<RepoResponse<int>> DeactivateAsync(int hairdresserId, DeactivateRequestDto updateRequest);
    }
}