//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Entities;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Dtos.ServicePrice;
using System.Threading.Tasks;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.HairdresserManagementModule.Application.Interfaces.Repositories
{
    public partial interface IServicePriceRepository : IBaseRepository<ServicePriceDto>
    {
        Task<RepoResponse<ServicePriceDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByServiceIdResponseDto>>> GetByServiceIdAsync(int servicePriceServiceId, int? pageNumber = null, int? pageSize = null);
    }
}