//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Entities;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Dtos.Service;
using System.Threading.Tasks;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.HairdresserManagementModule.Application.Interfaces.Repositories
{
    public partial interface IServiceRepository : IBaseRepository<ServiceDto>
    {
        Task<RepoResponse<ServiceDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByHairdresserIdResponseDto>>> GetByHairdresserIdAsync(int serviceHairdresserId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByCategoryResponseDto>>> GetByCategoryAsync(ServiceCategory serviceCategory, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetServicePricesForServicesResponseDto>>> GetServicePricesForServicesAsync(int servicesId);
        Task<RepoResponse<GetServicePricesForServicesResponseDto>> GetServicePricesForServicesDetailsAsync(int servicesId, int servicePricesId);
        Task<RepoResponse<int>> UpdatePriceAsync(int serviceId, UpdatePriceRequestDto updateRequest);
    }
}