SELECT [ID], [NOTE], [CREATED_DATE] 
FROM [CUSTOMER_NOTES] 
WHERE [IsDeleted] = 0 
	AND [CUSTOMER_ID] = @PRM_CUSTOMER_NOTE_CUSTOMER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 