SELECT PC.[PRODUCT_ID], PC.[CATEGORY_ID] 
FROM [PRODUCT_CATEGORIES] PC 
WHERE PC.[PRODUCT_ID] = @PRM_PRODUCT_CATEGORY_PRODUCT_ID 
ORDER BY PC.[PRODUCT_ID], PC.[CATEGORY_ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 