//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Entities;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.HairdresserManagementModule.Persistence.Contexts;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Dtos.SalonEquipment;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Mappings;
using QuickCode.DemoAi.HairdresserManagementModule.Persistence.Sql;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.HairdresserManagementModule.Persistence.Repositories
{
    public partial class SalonEquipmentRepository : BaseRepository, ISalonEquipmentRepository
    {
        public async Task<RepoResponse<int>> UpdateQuantityAsync(int salonEquipmentId, UpdateQuantityRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("SalonEquipment", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SalonEquipment.Command.UpdateQuantity);
                var parameters = new
                {
                    SALON_EQUIPMENT_QUANTITY = updateRequest.SalonEquipmentQuantity,
                    PRM_SALON_EQUIPMENT_ID = salonEquipmentId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}