//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.ShippingModule.Domain.Entities;
using QuickCode.DemoAi.ShippingModule.Application.Dtos.Shipment;
using System.Threading.Tasks;
using QuickCode.DemoAi.ShippingModule.Domain.Enums;

namespace QuickCode.DemoAi.ShippingModule.Application.Interfaces.Repositories
{
    public partial interface IShipmentRepository : IBaseRepository<ShipmentDto>
    {
        Task<RepoResponse<ShipmentDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetByOrderIdResponseDto>> GetByOrderIdAsync(int shipmentOrderId);
        Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(ShippingStatus shipmentStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> UpdateStatusAsync(int shipmentId, UpdateStatusRequestDto updateRequest);
    }
}