SELECT [ID], [NOTE], [CREATED_DATE] 
FROM [HAIRDRESSER_NOTES] 
WHERE [IsDeleted] = 0 
	AND [HAIRDRESSER_ID] = @PRM_HAIRDRESSER_NOTE_HAIRDRESSER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 