//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoAi.CustomerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.CustomerManagementModule.Persistence.Contexts;
using QuickCode.DemoAi.CustomerManagementModule.Application.Dtos.Customer;
using QuickCode.DemoAi.CustomerManagementModule.Application.Mappings;
using QuickCode.DemoAi.CustomerManagementModule.Persistence.Sql;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.CustomerManagementModule.Persistence.Repositories
{
    public partial class CustomerRepository : BaseRepository, ICustomerRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool customerIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetActive", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CUSTOMER_IS_ACTIVE = customerIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Customer");
                }
            });
        }

        public async Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string customerFirstName, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("SearchByName", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SearchByNameResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Customer.Query.SearchByName);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CUSTOMER_FIRST_NAME = customerFirstName,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<SearchByNameResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Customer");
                }
            });
        }

        public async Task<RepoResponse<List<GetCustomerAddressesForCustomersResponseDto>>> GetCustomerAddressesForCustomersAsync(int customersId)
        {
            return await ExecuteWithExceptionHandling("GetCustomerAddressesForCustomers", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetCustomerAddressesForCustomers);
                var parameters = new
                {
                    customersId = customersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetCustomerAddressesForCustomersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Customer");
            });
        }

        public async Task<RepoResponse<GetCustomerAddressesForCustomersResponseDto>> GetCustomerAddressesForCustomersDetailsAsync(int customersId, int customerAddressesId)
        {
            return await ExecuteWithExceptionHandling("GetCustomerAddressesForCustomersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetCustomerAddressesForCustomersDetails);
                var parameters = new
                {
                    customersId = customersId,
                    customerAddressesId = customerAddressesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetCustomerAddressesForCustomersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Customer");
            });
        }

        public async Task<RepoResponse<List<GetCustomerNotesForCustomersResponseDto>>> GetCustomerNotesForCustomersAsync(int customersId)
        {
            return await ExecuteWithExceptionHandling("GetCustomerNotesForCustomers", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetCustomerNotesForCustomers);
                var parameters = new
                {
                    customersId = customersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetCustomerNotesForCustomersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Customer");
            });
        }

        public async Task<RepoResponse<GetCustomerNotesForCustomersResponseDto>> GetCustomerNotesForCustomersDetailsAsync(int customersId, int customerNotesId)
        {
            return await ExecuteWithExceptionHandling("GetCustomerNotesForCustomersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetCustomerNotesForCustomersDetails);
                var parameters = new
                {
                    customersId = customersId,
                    customerNotesId = customerNotesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetCustomerNotesForCustomersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Customer");
            });
        }

        public async Task<RepoResponse<List<GetCustomerPreferencesForCustomersResponseDto>>> GetCustomerPreferencesForCustomersAsync(int customersId)
        {
            return await ExecuteWithExceptionHandling("GetCustomerPreferencesForCustomers", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetCustomerPreferencesForCustomers);
                var parameters = new
                {
                    customersId = customersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetCustomerPreferencesForCustomersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Customer");
            });
        }

        public async Task<RepoResponse<GetCustomerPreferencesForCustomersResponseDto>> GetCustomerPreferencesForCustomersDetailsAsync(int customersId, int customerPreferencesId)
        {
            return await ExecuteWithExceptionHandling("GetCustomerPreferencesForCustomersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetCustomerPreferencesForCustomersDetails);
                var parameters = new
                {
                    customersId = customersId,
                    customerPreferencesId = customerPreferencesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetCustomerPreferencesForCustomersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Customer");
            });
        }

        public async Task<RepoResponse<List<GetCustomerLoyaltyPointsForCustomersResponseDto>>> GetCustomerLoyaltyPointsForCustomersAsync(int customersId)
        {
            return await ExecuteWithExceptionHandling("GetCustomerLoyaltyPointsForCustomers", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetCustomerLoyaltyPointsForCustomers);
                var parameters = new
                {
                    customersId = customersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetCustomerLoyaltyPointsForCustomersResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Customer");
            });
        }

        public async Task<RepoResponse<GetCustomerLoyaltyPointsForCustomersResponseDto>> GetCustomerLoyaltyPointsForCustomersDetailsAsync(int customersId, int customerLoyaltyPointsId)
        {
            return await ExecuteWithExceptionHandling("GetCustomerLoyaltyPointsForCustomersDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Customer.Query.GetCustomerLoyaltyPointsForCustomersDetails);
                var parameters = new
                {
                    customersId = customersId,
                    customerLoyaltyPointsId = customerLoyaltyPointsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetCustomerLoyaltyPointsForCustomersResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Customer");
            });
        }
    }
}