SELECT O.[ID], O.[ORDER_DATE], O.[TOTAL_AMOUNT], O.[STATUS] 
FROM [ORDERS] O 
WHERE O.[IsDeleted] = 0 
	AND O.[USER_ID] = @PRM_ORDER_USER_ID 
ORDER BY O.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 