//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.IdentityModule.Domain.Entities;
using QuickCode.DemoAi.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.IdentityModule.Persistence.Contexts;
using QuickCode.DemoAi.IdentityModule.Application.Dtos.KafkaEvent;
using QuickCode.DemoAi.IdentityModule.Application.Mappings;
using QuickCode.DemoAi.IdentityModule.Persistence.Sql;
using QuickCode.DemoAi.IdentityModule.Domain.Enums;

namespace QuickCode.DemoAi.IdentityModule.Persistence.Repositories
{
    public partial class KafkaEventRepository : BaseRepository, IKafkaEventRepository
    {
        public async Task<RepoResponse<int>> CleanKafkaEventsWithModuleNameAsync(string apiMethodDefinitionsModuleName)
        {
            return await ExecuteWithExceptionHandling("KafkaEvent", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Command.CleanKafkaEventsWithModuleName);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_ModuleName = apiMethodDefinitionsModuleName
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> CleanKafkaEventsWithModelNameAsync(string apiMethodDefinitionsModelName)
        {
            return await ExecuteWithExceptionHandling("KafkaEvent", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Command.CleanKafkaEventsWithModelName);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_ModelName = apiMethodDefinitionsModelName
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}