//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.OrderModule.Application.Dtos.OrderItem;
using QuickCode.DemoAi.OrderModule.Domain.Entities;
using QuickCode.DemoAi.OrderModule.Domain.Enums;

namespace QuickCode.DemoAi.OrderModule.Application.Mappings
{
    public static class OrderItemMappings
    {
        public static List<OrderItemDto> ToDto(this IEnumerable<OrderItem> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static OrderItemDto ToDto(this OrderItem model)
        {
            return new OrderItemDto
            {
                Id = model.Id,
                OrderId = model.OrderId,
                ProductId = model.ProductId,
                Quantity = model.Quantity,
                Price = model.Price
            };
        }

        public static OrderItem ToEntity(this OrderItemDto model)
        {
            return new OrderItem
            {
                Id = model.Id,
                OrderId = model.OrderId,
                ProductId = model.ProductId,
                Quantity = model.Quantity,
                Price = model.Price
            };
        }
    }
}