//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.AppointmentManagementModule.Application.Dtos.AppointmentFeedback
{
    public record AppointmentFeedbackDto
    {
        public int Id { get; init; }
        public int AppointmentId { get; init; }
        public short Rating { get; init; }
        public string Comments { get; init; }
        public DateTime CreatedDate { get; init; }
    }
}