//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Entities;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.HairdresserManagementModule.Persistence.Contexts;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Dtos.Service;
using QuickCode.DemoAi.HairdresserManagementModule.Application.Mappings;
using QuickCode.DemoAi.HairdresserManagementModule.Persistence.Sql;
using QuickCode.DemoAi.HairdresserManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.HairdresserManagementModule.Persistence.Repositories
{
    public partial class ServiceRepository : BaseRepository, IServiceRepository
    {
        public async Task<RepoResponse<int>> UpdatePriceAsync(int serviceId, UpdatePriceRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Service", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Service.Command.UpdatePrice);
                var parameters = new
                {
                    SERVICE_PRICE = updateRequest.ServicePrice,
                    PRM_SERVICE_ID = serviceId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}