//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoAi.ProductCatalogModule.Application.Dtos.ProductCategory;
using QuickCode.DemoAi.ProductCatalogModule.Domain.Entities;
using QuickCode.DemoAi.ProductCatalogModule.Domain.Enums;

namespace QuickCode.DemoAi.ProductCatalogModule.Application.Mappings
{
    public static class ProductCategoryMappings
    {
        public static List<ProductCategoryDto> ToDto(this IEnumerable<ProductCategory> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ProductCategoryDto ToDto(this ProductCategory model)
        {
            return new ProductCategoryDto
            {
                ProductId = model.ProductId,
                CategoryId = model.CategoryId
            };
        }

        public static ProductCategory ToEntity(this ProductCategoryDto model)
        {
            return new ProductCategory
            {
                ProductId = model.ProductId,
                CategoryId = model.CategoryId
            };
        }
    }
}