SELECT [ID], [DAY_OF_WEEK], [START_TIME], [END_TIME] 
FROM [HAIRDRESSER_AVAILABILITIES] 
WHERE [IsDeleted] = 0 
	AND [HAIRDRESSER_ID] = @PRM_HAIRDRESSER_AVAILABILITY_HAIRDRESSER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 