//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.PaymentProcessingModule.Domain.Entities;
using QuickCode.DemoAi.PaymentProcessingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.PaymentProcessingModule.Persistence.Contexts;
using QuickCode.DemoAi.PaymentProcessingModule.Application.Dtos.Payment;
using QuickCode.DemoAi.PaymentProcessingModule.Application.Mappings;
using QuickCode.DemoAi.PaymentProcessingModule.Persistence.Sql;
using QuickCode.DemoAi.PaymentProcessingModule.Domain.Enums;

namespace QuickCode.DemoAi.PaymentProcessingModule.Persistence.Repositories
{
    public partial class PaymentRepository : BaseRepository, IPaymentRepository
    {
        public async Task<RepoResponse<int>> UpdateStatusAsync(int paymentId, UpdateStatusRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Payment", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Payment.Command.UpdateStatus);
                var parameters = new
                {
                    PAYMENT_STATUS = updateRequest.PaymentStatus,
                    PRM_PAYMENT_ID = paymentId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}