//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.PaymentProcessingModule.Domain.Entities;
using QuickCode.DemoAi.PaymentProcessingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.PaymentProcessingModule.Persistence.Contexts;
using QuickCode.DemoAi.PaymentProcessingModule.Application.Dtos.Payment;
using QuickCode.DemoAi.PaymentProcessingModule.Application.Mappings;
using QuickCode.DemoAi.PaymentProcessingModule.Persistence.Sql;
using QuickCode.DemoAi.PaymentProcessingModule.Domain.Enums;

namespace QuickCode.DemoAi.PaymentProcessingModule.Persistence.Repositories
{
    public partial class PaymentRepository : BaseRepository, IPaymentRepository
    {
        public async Task<RepoResponse<GetByOrderIdResponseDto>> GetByOrderIdAsync(int paymentOrderId)
        {
            return await ExecuteWithExceptionHandling("GetByOrderId", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Payment.Query.GetByOrderId);
                var parameters = new
                {
                    PRM_PAYMENT_ORDER_ID = paymentOrderId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetByOrderIdResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Payment");
            });
        }

        public async Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(PaymentStatus paymentStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByStatus", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByStatusResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Payment.Query.GetByStatus);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PAYMENT_STATUS = paymentStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByStatusResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Payment");
                }
            });
        }

        public async Task<RepoResponse<List<GetPaymentsByDateRangeResponseDto>>> GetPaymentsByDateRangeAsync(DateTime paymentPaymentDateFrom, DateTime paymentPaymentDateTo, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetPaymentsByDateRange", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetPaymentsByDateRangeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Payment.Query.GetPaymentsByDateRange);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PAYMENT_PAYMENT_DATE_From = paymentPaymentDateFrom,
                        PRM_PAYMENT_PAYMENT_DATE_To = paymentPaymentDateTo,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetPaymentsByDateRangeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Payment");
                }
            });
        }
    }
}