//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoAi.CustomerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.CustomerManagementModule.Persistence.Contexts;
using QuickCode.DemoAi.CustomerManagementModule.Application.Dtos.LoyaltyProgram;
using QuickCode.DemoAi.CustomerManagementModule.Application.Mappings;
using QuickCode.DemoAi.CustomerManagementModule.Persistence.Sql;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.CustomerManagementModule.Persistence.Repositories
{
    public partial class LoyaltyProgramRepository : BaseRepository, ILoyaltyProgramRepository
    {
        public async Task<RepoResponse<List<GetAllResponseDto>>> GetAllAsync()
        {
            return await ExecuteWithExceptionHandling("GetAll", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoyaltyProgram.Query.GetAll);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetAllResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in LoyaltyProgram");
            });
        }

        public async Task<RepoResponse<List<GetCustomerLoyaltyPointsForLoyaltyProgramsResponseDto>>> GetCustomerLoyaltyPointsForLoyaltyProgramsAsync(int loyaltyProgramsId)
        {
            return await ExecuteWithExceptionHandling("GetCustomerLoyaltyPointsForLoyaltyPrograms", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoyaltyProgram.Query.GetCustomerLoyaltyPointsForLoyaltyPrograms);
                var parameters = new
                {
                    loyaltyProgramsId = loyaltyProgramsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetCustomerLoyaltyPointsForLoyaltyProgramsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in LoyaltyProgram");
            });
        }

        public async Task<RepoResponse<GetCustomerLoyaltyPointsForLoyaltyProgramsResponseDto>> GetCustomerLoyaltyPointsForLoyaltyProgramsDetailsAsync(int loyaltyProgramsId, int customerLoyaltyPointsId)
        {
            return await ExecuteWithExceptionHandling("GetCustomerLoyaltyPointsForLoyaltyProgramsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.LoyaltyProgram.Query.GetCustomerLoyaltyPointsForLoyaltyProgramsDetails);
                var parameters = new
                {
                    loyaltyProgramsId = loyaltyProgramsId,
                    customerLoyaltyPointsId = customerLoyaltyPointsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetCustomerLoyaltyPointsForLoyaltyProgramsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in LoyaltyProgram");
            });
        }
    }
}