//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.IdentityModule.Domain.Entities;
using QuickCode.DemoAi.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.IdentityModule.Persistence.Contexts;
using QuickCode.DemoAi.IdentityModule.Application.Dtos.ApiMethodDefinition;
using QuickCode.DemoAi.IdentityModule.Application.Mappings;
using QuickCode.DemoAi.IdentityModule.Persistence.Sql;
using QuickCode.DemoAi.IdentityModule.Domain.Enums;

namespace QuickCode.DemoAi.IdentityModule.Persistence.Repositories
{
    public partial class ApiMethodDefinitionRepository : BaseRepository, IApiMethodDefinitionRepository
    {
        public async Task<RepoResponse<int>> DeleteApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionModuleName)
        {
            return await ExecuteWithExceptionHandling("ApiMethodDefinition", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Command.DeleteApiMethodDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModuleName = apiMethodDefinitionModuleName
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> DeleteApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionModelName)
        {
            return await ExecuteWithExceptionHandling("ApiMethodDefinition", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Command.DeleteApiMethodDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModelName = apiMethodDefinitionModelName
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}