//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Entities;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Dtos.Appointment;
using System.Threading.Tasks;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.AppointmentManagementModule.Application.Interfaces.Repositories
{
    public partial interface IAppointmentRepository : IBaseRepository<AppointmentDto>
    {
        Task<RepoResponse<AppointmentDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByCustomerIdResponseDto>>> GetByCustomerIdAsync(int appointmentCustomerId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByServiceIdResponseDto>>> GetByServiceIdAsync(int appointmentServiceId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByDateRangeResponseDto>>> GetByDateRangeAsync(DateTime appointmentAppointmentDateFrom, DateTime appointmentAppointmentDateTo, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetAppointmentFeedbacksForAppointmentsResponseDto>>> GetAppointmentFeedbacksForAppointmentsAsync(int appointmentsId);
        Task<RepoResponse<GetAppointmentFeedbacksForAppointmentsResponseDto>> GetAppointmentFeedbacksForAppointmentsDetailsAsync(int appointmentsId, int appointmentFeedbacksId);
        Task<RepoResponse<List<GetAppointmentRemindersForAppointmentsResponseDto>>> GetAppointmentRemindersForAppointmentsAsync(int appointmentsId);
        Task<RepoResponse<GetAppointmentRemindersForAppointmentsResponseDto>> GetAppointmentRemindersForAppointmentsDetailsAsync(int appointmentsId, int appointmentRemindersId);
        Task<RepoResponse<List<GetAppointmentChargesForAppointmentsResponseDto>>> GetAppointmentChargesForAppointmentsAsync(int appointmentsId);
        Task<RepoResponse<GetAppointmentChargesForAppointmentsResponseDto>> GetAppointmentChargesForAppointmentsDetailsAsync(int appointmentsId, int appointmentChargesId);
        Task<RepoResponse<int>> ConfirmAsync(int appointmentId, ConfirmRequestDto updateRequest);
        Task<RepoResponse<int>> CancelAsync(int appointmentId, CancelRequestDto updateRequest);
    }
}