//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Entities;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Dtos.Holiday;
using System.Threading.Tasks;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.AppointmentManagementModule.Application.Interfaces.Repositories
{
    public partial interface IHolidayRepository : IBaseRepository<HolidayDto>
    {
        Task<RepoResponse<HolidayDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetAllResponseDto>>> GetAllAsync();
    }
}