//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.IdentityModule.Domain.Entities;
using QuickCode.DemoAi.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.IdentityModule.Persistence.Contexts;
using QuickCode.DemoAi.IdentityModule.Application.Dtos.PortalPageDefinition;
using QuickCode.DemoAi.IdentityModule.Application.Mappings;
using QuickCode.DemoAi.IdentityModule.Persistence.Sql;
using QuickCode.DemoAi.IdentityModule.Domain.Enums;

namespace QuickCode.DemoAi.IdentityModule.Persistence.Repositories
{
    public partial class PortalPageDefinitionRepository : BaseRepository, IPortalPageDefinitionRepository
    {
        public async Task<RepoResponse<int>> DeletePortalPageDefinitionsWithModuleNameAsync(string portalPageDefinitionModuleName)
        {
            return await ExecuteWithExceptionHandling("PortalPageDefinition", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Command.DeletePortalPageDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_PortalPageDefinition_ModuleName = portalPageDefinitionModuleName
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> DeletePortalPageDefinitionsWithModelNameAsync(string portalPageDefinitionModelName)
        {
            return await ExecuteWithExceptionHandling("PortalPageDefinition", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Command.DeletePortalPageDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_PortalPageDefinition_ModelName = portalPageDefinitionModelName
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}