//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoAi.CustomerManagementModule.Application.Dtos.CustomerLoyaltyPoint;
using System.Threading.Tasks;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.CustomerManagementModule.Application.Interfaces.Repositories
{
    public partial interface ICustomerLoyaltyPointRepository : IBaseRepository<CustomerLoyaltyPointDto>
    {
        Task<RepoResponse<CustomerLoyaltyPointDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByCustomerIdResponseDto>>> GetByCustomerIdAsync(int customerLoyaltyPointCustomerId, int? pageNumber = null, int? pageSize = null);
    }
}