//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoAi.CustomerManagementModule.Application.Dtos.Customer;
using System.Threading.Tasks;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.CustomerManagementModule.Application.Interfaces.Repositories
{
    public partial interface ICustomerRepository : IBaseRepository<CustomerDto>
    {
        Task<RepoResponse<CustomerDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool customerIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string customerFirstName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetCustomerAddressesForCustomersResponseDto>>> GetCustomerAddressesForCustomersAsync(int customersId);
        Task<RepoResponse<GetCustomerAddressesForCustomersResponseDto>> GetCustomerAddressesForCustomersDetailsAsync(int customersId, int customerAddressesId);
        Task<RepoResponse<List<GetCustomerNotesForCustomersResponseDto>>> GetCustomerNotesForCustomersAsync(int customersId);
        Task<RepoResponse<GetCustomerNotesForCustomersResponseDto>> GetCustomerNotesForCustomersDetailsAsync(int customersId, int customerNotesId);
        Task<RepoResponse<List<GetCustomerPreferencesForCustomersResponseDto>>> GetCustomerPreferencesForCustomersAsync(int customersId);
        Task<RepoResponse<GetCustomerPreferencesForCustomersResponseDto>> GetCustomerPreferencesForCustomersDetailsAsync(int customersId, int customerPreferencesId);
        Task<RepoResponse<List<GetCustomerLoyaltyPointsForCustomersResponseDto>>> GetCustomerLoyaltyPointsForCustomersAsync(int customersId);
        Task<RepoResponse<GetCustomerLoyaltyPointsForCustomersResponseDto>> GetCustomerLoyaltyPointsForCustomersDetailsAsync(int customersId, int customerLoyaltyPointsId);
        Task<RepoResponse<int>> ActivateAsync(int customerId, ActivateRequestDto updateRequest);
        Task<RepoResponse<int>> DeactivateAsync(int customerId, DeactivateRequestDto updateRequest);
    }
}