//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Entities;
using QuickCode.DemoAi.CustomerManagementModule.Application.Dtos.LoyaltyProgram;
using System.Threading.Tasks;
using QuickCode.DemoAi.CustomerManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.CustomerManagementModule.Application.Interfaces.Repositories
{
    public partial interface ILoyaltyProgramRepository : IBaseRepository<LoyaltyProgramDto>
    {
        Task<RepoResponse<LoyaltyProgramDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetAllResponseDto>>> GetAllAsync();
        Task<RepoResponse<List<GetCustomerLoyaltyPointsForLoyaltyProgramsResponseDto>>> GetCustomerLoyaltyPointsForLoyaltyProgramsAsync(int loyaltyProgramsId);
        Task<RepoResponse<GetCustomerLoyaltyPointsForLoyaltyProgramsResponseDto>> GetCustomerLoyaltyPointsForLoyaltyProgramsDetailsAsync(int loyaltyProgramsId, int customerLoyaltyPointsId);
    }
}