SELECT C.[ID], C.[NAME], C.[DESCRIPTION] 
FROM [CATEGORIES] C 
WHERE C.[IsDeleted] = 0 
	AND C.[NAME] LIKE '%' + @PRM_CATEGORY_NAME + '%' 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 