SELECT P.[ID], P.[ORDER_ID], P.[PAYMENT_DATE], P.[AMOUNT], P.[PAYMENT_METHOD] 
FROM [PAYMENTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[STATUS] = @PRM_PAYMENT_STATUS 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 