SELECT P.[ID], P.[ORDER_ID], P.[PAYMENT_DATE], P.[AMOUNT], P.[STATUS] 
FROM [PAYMENTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[PAYMENT_DATE] BETWEEN @PRM_PAYMENT_PAYMENT_DATE_From 
	AND @PRM_PAYMENT_PAYMENT_DATE_To 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 