//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.OrderModule.Domain.Entities;
using QuickCode.DemoAi.OrderModule.Application.Dtos.OrderItem;
using System.Threading.Tasks;
using QuickCode.DemoAi.OrderModule.Domain.Enums;

namespace QuickCode.DemoAi.OrderModule.Application.Interfaces.Repositories
{
    public partial interface IOrderItemRepository : IBaseRepository<OrderItemDto>
    {
        Task<RepoResponse<OrderItemDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByOrderResponseDto>>> GetByOrderAsync(int orderItemOrderId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByProductResponseDto>>> GetByProductAsync(int orderItemProductId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<long>> GetTotalQuantityByProductAsync(int orderItemProductId);
    }
}