//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.IdentityModule.Domain.Entities;
using QuickCode.DemoAi.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.IdentityModule.Persistence.Contexts;
using QuickCode.DemoAi.IdentityModule.Application.Dtos.TopicWorkflow;
using QuickCode.DemoAi.IdentityModule.Application.Mappings;
using QuickCode.DemoAi.IdentityModule.Persistence.Sql;
using QuickCode.DemoAi.IdentityModule.Domain.Enums;

namespace QuickCode.DemoAi.IdentityModule.Persistence.Repositories
{
    public partial class TopicWorkflowRepository : BaseRepository, ITopicWorkflowRepository
    {
        public async Task<RepoResponse<List<GetWorkflowsResponseDto>>> GetWorkflowsAsync(string topicWorkflowKafkaEventsTopicName)
        {
            return await ExecuteWithExceptionHandling("GetWorkflows", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TopicWorkflow.Query.GetWorkflows);
                var parameters = new
                {
                    PRM_TopicWorkflow_KafkaEventsTopicName = topicWorkflowKafkaEventsTopicName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetWorkflowsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in TopicWorkflow");
            });
        }

        public async Task<RepoResponse<List<GetWorkflows2ResponseDto>>> GetWorkflows2Async(string topicWorkflowKafkaEventsTopicName)
        {
            return await ExecuteWithExceptionHandling("GetWorkflows2", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TopicWorkflow.Query.GetWorkflows2);
                var parameters = new
                {
                    PRM_TopicWorkflow_KafkaEventsTopicName = topicWorkflowKafkaEventsTopicName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetWorkflows2ResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in TopicWorkflow");
            });
        }

        public async Task<RepoResponse<List<GetTopicWorkflowsResponseDto>>> GetTopicWorkflowsAsync(string kafkaEventsTopicName, HttpMethodType apiMethodDefinitionsHttpMethod)
        {
            return await ExecuteWithExceptionHandling("GetTopicWorkflows", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TopicWorkflow.Query.GetTopicWorkflows);
                var parameters = new
                {
                    PRM_KafkaEvents_TopicName = kafkaEventsTopicName,
                    PRM_ApiMethodDefinitions_HttpMethod = apiMethodDefinitionsHttpMethod
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetTopicWorkflowsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in TopicWorkflow");
            });
        }
    }
}