//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.PaymentProcessingModule.Domain.Entities;
using QuickCode.DemoAi.PaymentProcessingModule.Application.Dtos.Payment;
using System.Threading.Tasks;
using QuickCode.DemoAi.PaymentProcessingModule.Domain.Enums;

namespace QuickCode.DemoAi.PaymentProcessingModule.Application.Interfaces.Repositories
{
    public partial interface IPaymentRepository : IBaseRepository<PaymentDto>
    {
        Task<RepoResponse<PaymentDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetByOrderIdResponseDto>> GetByOrderIdAsync(int paymentOrderId);
        Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(PaymentStatus paymentStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPaymentsByDateRangeResponseDto>>> GetPaymentsByDateRangeAsync(DateTime paymentPaymentDateFrom, DateTime paymentPaymentDateTo, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> UpdateStatusAsync(int paymentId, UpdateStatusRequestDto updateRequest);
    }
}