SELECT [ID], [CHARGE_TYPE], [AMOUNT] 
FROM [APPOINTMENT_CHARGES] 
WHERE [IsDeleted] = 0 
	AND [APPOINTMENT_ID] = @PRM_APPOINTMENT_CHARGE_APPOINTMENT_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 