//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Entities;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.AppointmentManagementModule.Persistence.Contexts;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Dtos.Appointment;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Mappings;
using QuickCode.DemoAi.AppointmentManagementModule.Persistence.Sql;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.AppointmentManagementModule.Persistence.Repositories
{
    public partial class AppointmentRepository : BaseRepository, IAppointmentRepository
    {
        public async Task<RepoResponse<List<GetByCustomerIdResponseDto>>> GetByCustomerIdAsync(int appointmentCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByCustomerId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCustomerIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Appointment.Query.GetByCustomerId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_APPOINTMENT_CUSTOMER_ID = appointmentCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByCustomerIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Appointment");
                }
            });
        }

        public async Task<RepoResponse<List<GetByServiceIdResponseDto>>> GetByServiceIdAsync(int appointmentServiceId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByServiceId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByServiceIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Appointment.Query.GetByServiceId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_APPOINTMENT_SERVICE_ID = appointmentServiceId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByServiceIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Appointment");
                }
            });
        }

        public async Task<RepoResponse<List<GetByDateRangeResponseDto>>> GetByDateRangeAsync(DateTime appointmentAppointmentDateFrom, DateTime appointmentAppointmentDateTo, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByDateRange", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByDateRangeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Appointment.Query.GetByDateRange);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_APPOINTMENT_APPOINTMENT_DATE_From = appointmentAppointmentDateFrom,
                        PRM_APPOINTMENT_APPOINTMENT_DATE_To = appointmentAppointmentDateTo,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByDateRangeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Appointment");
                }
            });
        }

        public async Task<RepoResponse<List<GetAppointmentFeedbacksForAppointmentsResponseDto>>> GetAppointmentFeedbacksForAppointmentsAsync(int appointmentsId)
        {
            return await ExecuteWithExceptionHandling("GetAppointmentFeedbacksForAppointments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Appointment.Query.GetAppointmentFeedbacksForAppointments);
                var parameters = new
                {
                    appointmentsId = appointmentsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetAppointmentFeedbacksForAppointmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Appointment");
            });
        }

        public async Task<RepoResponse<GetAppointmentFeedbacksForAppointmentsResponseDto>> GetAppointmentFeedbacksForAppointmentsDetailsAsync(int appointmentsId, int appointmentFeedbacksId)
        {
            return await ExecuteWithExceptionHandling("GetAppointmentFeedbacksForAppointmentsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Appointment.Query.GetAppointmentFeedbacksForAppointmentsDetails);
                var parameters = new
                {
                    appointmentsId = appointmentsId,
                    appointmentFeedbacksId = appointmentFeedbacksId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetAppointmentFeedbacksForAppointmentsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Appointment");
            });
        }

        public async Task<RepoResponse<List<GetAppointmentRemindersForAppointmentsResponseDto>>> GetAppointmentRemindersForAppointmentsAsync(int appointmentsId)
        {
            return await ExecuteWithExceptionHandling("GetAppointmentRemindersForAppointments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Appointment.Query.GetAppointmentRemindersForAppointments);
                var parameters = new
                {
                    appointmentsId = appointmentsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetAppointmentRemindersForAppointmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Appointment");
            });
        }

        public async Task<RepoResponse<GetAppointmentRemindersForAppointmentsResponseDto>> GetAppointmentRemindersForAppointmentsDetailsAsync(int appointmentsId, int appointmentRemindersId)
        {
            return await ExecuteWithExceptionHandling("GetAppointmentRemindersForAppointmentsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Appointment.Query.GetAppointmentRemindersForAppointmentsDetails);
                var parameters = new
                {
                    appointmentsId = appointmentsId,
                    appointmentRemindersId = appointmentRemindersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetAppointmentRemindersForAppointmentsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Appointment");
            });
        }

        public async Task<RepoResponse<List<GetAppointmentChargesForAppointmentsResponseDto>>> GetAppointmentChargesForAppointmentsAsync(int appointmentsId)
        {
            return await ExecuteWithExceptionHandling("GetAppointmentChargesForAppointments", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Appointment.Query.GetAppointmentChargesForAppointments);
                var parameters = new
                {
                    appointmentsId = appointmentsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetAppointmentChargesForAppointmentsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Appointment");
            });
        }

        public async Task<RepoResponse<GetAppointmentChargesForAppointmentsResponseDto>> GetAppointmentChargesForAppointmentsDetailsAsync(int appointmentsId, int appointmentChargesId)
        {
            return await ExecuteWithExceptionHandling("GetAppointmentChargesForAppointmentsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Appointment.Query.GetAppointmentChargesForAppointmentsDetails);
                var parameters = new
                {
                    appointmentsId = appointmentsId,
                    appointmentChargesId = appointmentChargesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetAppointmentChargesForAppointmentsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Appointment");
            });
        }
    }
}