//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Entities;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.AppointmentManagementModule.Persistence.Contexts;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Dtos.Appointment;
using QuickCode.DemoAi.AppointmentManagementModule.Application.Mappings;
using QuickCode.DemoAi.AppointmentManagementModule.Persistence.Sql;
using QuickCode.DemoAi.AppointmentManagementModule.Domain.Enums;

namespace QuickCode.DemoAi.AppointmentManagementModule.Persistence.Repositories
{
    public partial class AppointmentRepository : BaseRepository, IAppointmentRepository
    {
        public async Task<RepoResponse<int>> ConfirmAsync(int appointmentId, ConfirmRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Appointment", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Appointment.Command.Confirm);
                var parameters = new
                {
                    PRM_APPOINTMENT_ID = appointmentId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> CancelAsync(int appointmentId, CancelRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Appointment", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Appointment.Command.Cancel);
                var parameters = new
                {
                    PRM_APPOINTMENT_ID = appointmentId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}