SELECT [ID], [CUSTOMER_ID], [APPOINTMENT_DATE], [STATUS], [NOTES] 
FROM [APPOINTMENTS] 
WHERE [IsDeleted] = 0 
	AND [SERVICE_ID] = @PRM_APPOINTMENT_SERVICE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 