SELECT [ID], [SERVICE_ID], [APPOINTMENT_DATE], [STATUS], [NOTES] 
FROM [APPOINTMENTS] 
WHERE [IsDeleted] = 0 
	AND [CUSTOMER_ID] = @PRM_APPOINTMENT_CUSTOMER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 