SELECT [ID], [CUSTOMER_ID], [SERVICE_ID], [STATUS], [NOTES] 
FROM [APPOINTMENTS] 
WHERE [IsDeleted] = 0 
	AND [APPOINTMENT_DATE] BETWEEN @PRM_APPOINTMENT_APPOINTMENT_DATE_From 
	AND @PRM_APPOINTMENT_APPOINTMENT_DATE_To 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 