SELECT [ID], [ADDRESS_LINE_1], [ADDRESS_LINE_2], [CITY], [STATE], [ZIP_CODE], [COUNTRY], [IS_DEFAULT] 
FROM [CUSTOMER_ADDRESSES] 
WHERE [IsDeleted] = 0 
	AND [CUSTOMER_ID] = @PRM_CUSTOMER_ADDRESS_CUSTOMER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 