SELECT TOP 1 [ID], [ADDRESS_LINE_1], [CITY], [COUNTRY] 
FROM [CUSTOMER_ADDRESSES] 
WHERE [IsDeleted] = 0 
	AND [CUSTOMER_ID] = @PRM_CUSTOMER_ADDRESS_CUSTOMER_ID 
	AND [IS_DEFAULT] = @PRM_CUSTOMER_ADDRESS_IS_DEFAULT 
ORDER BY [ID] 