SELECT [ID], [CUSTOMER_ID], [PREFERRED_DATE], [NOTES] 
FROM [WAITING_LISTS] 
WHERE [IsDeleted] = 0 
	AND [SERVICE_ID] = @PRM_WAITING_LIST_SERVICE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 