//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.OrderModule.Domain.Entities;
using QuickCode.DemoAi.OrderModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoAi.Common;
using QuickCode.DemoAi.Common.Extensions;
using QuickCode.DemoAi.Common.Helpers;
using QuickCode.DemoAi.OrderModule.Persistence.Contexts;
using QuickCode.DemoAi.OrderModule.Application.Dtos.OrderItem;
using QuickCode.DemoAi.OrderModule.Application.Mappings;
using QuickCode.DemoAi.OrderModule.Persistence.Sql;
using QuickCode.DemoAi.OrderModule.Domain.Enums;

namespace QuickCode.DemoAi.OrderModule.Persistence.Repositories
{
    public partial class OrderItemRepository : BaseRepository, IOrderItemRepository
    {
        public async Task<RepoResponse<List<GetByOrderResponseDto>>> GetByOrderAsync(int orderItemOrderId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByOrder", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByOrderResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.OrderItem.Query.GetByOrder);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ORDER_ITEM_ORDER_ID = orderItemOrderId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByOrderResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in OrderItem");
                }
            });
        }

        public async Task<RepoResponse<List<GetByProductResponseDto>>> GetByProductAsync(int orderItemProductId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByProduct", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByProductResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.OrderItem.Query.GetByProduct);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ORDER_ITEM_PRODUCT_ID = orderItemProductId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByProductResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in OrderItem");
                }
            });
        }

        public async Task<RepoResponse<long>> GetTotalQuantityByProductAsync(int orderItemProductId)
        {
            return await ExecuteWithExceptionHandling("GetTotalQuantityByProduct", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OrderItem.Query.GetTotalQuantityByProduct);
                var parameters = new
                {
                    PRM_ORDER_ITEM_PRODUCT_ID = orderItemProductId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var result = await connection.ExecuteScalarAsync<long>(sql, parameters);
                return new RepoResponse<long>(result, "Success");
            });
        }
    }
}