SELECT OI.[ID], OI.[ORDER_ID], OI.[QUANTITY], OI.[PRICE] 
FROM [ORDER_ITEMS] OI 
WHERE OI.[IsDeleted] = 0 
	AND OI.[PRODUCT_ID] = @PRM_ORDER_ITEM_PRODUCT_ID 
ORDER BY OI.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 