//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoAi.Common.Models;
using QuickCode.DemoAi.IdentityModule.Domain.Entities;
using QuickCode.DemoAi.IdentityModule.Application.Dtos.PortalMenu;
using System.Threading.Tasks;
using QuickCode.DemoAi.IdentityModule.Domain.Enums;

namespace QuickCode.DemoAi.IdentityModule.Application.Interfaces.Repositories
{
    public partial interface IPortalMenuRepository : IBaseRepository<PortalMenuDto>
    {
        Task<RepoResponse<PortalMenuDto>> GetByPkAsync(string key);
        Task<RepoResponse<int>> DeletePortalMenuItemsWithModuleNameAsync(string portalMenuKey);
        Task<RepoResponse<int>> DeletePortalMenuItemsWithModelNameAsync(string portalMenuKey, string portalMenuName);
    }
}