SELECT [ID], [NAME], [EMAIL], [PHONE_NUMBER] 
FROM [HAIRDRESSERS] 
WHERE [IsDeleted] = 0 
	AND [IS_ACTIVE] = @PRM_HAIRDRESSER_IS_ACTIVE 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 