SELECT [ID], [NAME], [EMAIL], [PHONE_NUMBER] 
FROM [HAIRDRESSERS] 
WHERE [IsDeleted] = 0 
	AND [NAME] LIKE '%' + @PRM_HAIRDRESSER_NAME + '%' 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 